### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by nkh** [arkark/git-hist#15]
- optional taller commit information box
    - option to scroll in the commit information

- optional automatically jump to first diff
   - remember the position of the file already visited
  
- jump to next/previous diff

- show how many changes between the versions
    - show new/deleted files
    - show if it's a merge commit
   
- show multiple files
   - in tabs or split
   - when changing revision, stay on same file but show tabs for the other modified files

**Comment by arkark** [comment]
Thanks for opening an issue, but your requests are many and it is a lot of work to implement them all.
Since this project is an OSS, you have the choice to implement them yourself.

**Comment by nkh** [comment]
Given all the project re-implemented in rust, I've taken on myself to take project written in rust and re-implement them in bash and it's been  a lot of fun. This project may be my next victim ;)
